print ("Hello world my name is Manuel")
user_name = input ("What is your name?")
print ("Elephant, lion, cat")
print ("2")
print ("4")
print ("6")
input ("What is your adress?")
print ("Borders dissolve like salt in ocean's draft")
print ("Algorithms hum and stitch a thousand tongues")
print ("States and markets dance with fragile craft")
print ("While distant voices rise, untamed and young")
input ("Did you like my poem")
print ("See you soon")